/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    'root': RouteRecordInfo<'root', '/', Record<never, never>, Record<never, never>>,
    '$error': RouteRecordInfo<'$error', '/:error(.*)', { error: ParamValue<true> }, { error: ParamValue<false> }>,
    'cargas': RouteRecordInfo<'cargas', '/cargas', Record<never, never>, Record<never, never>>,
    'cargas-add': RouteRecordInfo<'cargas-add', '/cargas/add', Record<never, never>, Record<never, never>>,
    'cargas-details-id': RouteRecordInfo<'cargas-details-id', '/cargas/details/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'cargas-edit-id': RouteRecordInfo<'cargas-edit-id', '/cargas/edit/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'categories': RouteRecordInfo<'categories', '/categories', Record<never, never>, Record<never, never>>,
    'choferes': RouteRecordInfo<'choferes', '/choferes', Record<never, never>, Record<never, never>>,
    'choferes-add': RouteRecordInfo<'choferes-add', '/choferes/add', Record<never, never>, Record<never, never>>,
    'choferes-details-id': RouteRecordInfo<'choferes-details-id', '/choferes/details/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'choferes-edit-id': RouteRecordInfo<'choferes-edit-id', '/choferes/edit/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'combustibles': RouteRecordInfo<'combustibles', '/combustibles', Record<never, never>, Record<never, never>>,
    'combustibles-add': RouteRecordInfo<'combustibles-add', '/combustibles/add', Record<never, never>, Record<never, never>>,
    'combustibles-details-id': RouteRecordInfo<'combustibles-details-id', '/combustibles/details/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'combustibles-edit-id': RouteRecordInfo<'combustibles-edit-id', '/combustibles/edit/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'components-add-category': RouteRecordInfo<'components-add-category', '/components/AddCategory', Record<never, never>, Record<never, never>>,
    'components-add-subcategory': RouteRecordInfo<'components-add-subcategory', '/components/AddSubcategory', Record<never, never>, Record<never, never>>,
    'components-carga-combustible-dialog': RouteRecordInfo<'components-carga-combustible-dialog', '/components/CargaCombustibleDialog', Record<never, never>, Record<never, never>>,
    'components-cdt-report-generator': RouteRecordInfo<'components-cdt-report-generator', '/components/CdtReportGenerator', Record<never, never>, Record<never, never>>,
    'components-confirm-delete-dialog': RouteRecordInfo<'components-confirm-delete-dialog', '/components/ConfirmDeleteDialog', Record<never, never>, Record<never, never>>,
    'components-confirm-reason-delete-dialog': RouteRecordInfo<'components-confirm-reason-delete-dialog', '/components/ConfirmReasonDeleteDialog', Record<never, never>, Record<never, never>>,
    'components-pdf-export-dialog': RouteRecordInfo<'components-pdf-export-dialog', '/components/PdfExportDialog', Record<never, never>, Record<never, never>>,
    'components-retiro-combustible-dialog': RouteRecordInfo<'components-retiro-combustible-dialog', '/components/RetiroCombustibleDialog', Record<never, never>, Record<never, never>>,
    'components-select-tarjeta-dialog': RouteRecordInfo<'components-select-tarjeta-dialog', '/components/SelectTarjetaDialog', Record<never, never>, Record<never, never>>,
    'components-vehiculo-inoperatividad-dialog': RouteRecordInfo<'components-vehiculo-inoperatividad-dialog', '/components/VehiculoInoperatividadDialog', Record<never, never>, Record<never, never>>,
    'login': RouteRecordInfo<'login', '/login', Record<never, never>, Record<never, never>>,
    'products': RouteRecordInfo<'products', '/products', Record<never, never>, Record<never, never>>,
    'products-add': RouteRecordInfo<'products-add', '/products/add', Record<never, never>, Record<never, never>>,
    'products-details-id': RouteRecordInfo<'products-details-id', '/products/details/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'products-edit-id': RouteRecordInfo<'products-edit-id', '/products/edit/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'registro': RouteRecordInfo<'registro', '/registro', Record<never, never>, Record<never, never>>,
    'retiros': RouteRecordInfo<'retiros', '/retiros', Record<never, never>, Record<never, never>>,
    'retiros-add': RouteRecordInfo<'retiros-add', '/retiros/add', Record<never, never>, Record<never, never>>,
    'retiros-details-id': RouteRecordInfo<'retiros-details-id', '/retiros/details/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'retiros-edit-id': RouteRecordInfo<'retiros-edit-id', '/retiros/edit/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'second-page': RouteRecordInfo<'second-page', '/second-page', Record<never, never>, Record<never, never>>,
    'tarjetas': RouteRecordInfo<'tarjetas', '/tarjetas', Record<never, never>, Record<never, never>>,
    'tarjetas-add': RouteRecordInfo<'tarjetas-add', '/tarjetas/add', Record<never, never>, Record<never, never>>,
    'tarjetas-details-id': RouteRecordInfo<'tarjetas-details-id', '/tarjetas/details/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'tarjetas-edit-id': RouteRecordInfo<'tarjetas-edit-id', '/tarjetas/edit/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'usuarios': RouteRecordInfo<'usuarios', '/usuarios', Record<never, never>, Record<never, never>>,
    'usuarios-add': RouteRecordInfo<'usuarios-add', '/usuarios/add', Record<never, never>, Record<never, never>>,
    'usuarios-details-id': RouteRecordInfo<'usuarios-details-id', '/usuarios/details/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'usuarios-edit-id': RouteRecordInfo<'usuarios-edit-id', '/usuarios/edit/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'vehiculos': RouteRecordInfo<'vehiculos', '/vehiculos', Record<never, never>, Record<never, never>>,
    'vehiculos-add': RouteRecordInfo<'vehiculos-add', '/vehiculos/add', Record<never, never>, Record<never, never>>,
    'vehiculos-details-id': RouteRecordInfo<'vehiculos-details-id', '/vehiculos/details/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'vehiculos-edit-id': RouteRecordInfo<'vehiculos-edit-id', '/vehiculos/edit/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
  }
}
