/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    'root': RouteRecordInfo<'root', '/', Record<never, never>, Record<never, never>>,
    '$error': RouteRecordInfo<'$error', '/:error(.*)', { error: ParamValue<true> }, { error: ParamValue<false> }>,
    'categories': RouteRecordInfo<'categories', '/categories', Record<never, never>, Record<never, never>>,
    'components-add-category': RouteRecordInfo<'components-add-category', '/components/AddCategory', Record<never, never>, Record<never, never>>,
    'components-add-subcategory': RouteRecordInfo<'components-add-subcategory', '/components/AddSubcategory', Record<never, never>, Record<never, never>>,
    'components-confirm-delete-dialog': RouteRecordInfo<'components-confirm-delete-dialog', '/components/ConfirmDeleteDialog', Record<never, never>, Record<never, never>>,
    'login': RouteRecordInfo<'login', '/login', Record<never, never>, Record<never, never>>,
    'products': RouteRecordInfo<'products', '/products', Record<never, never>, Record<never, never>>,
    'products-add': RouteRecordInfo<'products-add', '/products/add', Record<never, never>, Record<never, never>>,
    'products-details-id': RouteRecordInfo<'products-details-id', '/products/details/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'products-edit-id': RouteRecordInfo<'products-edit-id', '/products/edit/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'second-page': RouteRecordInfo<'second-page', '/second-page', Record<never, never>, Record<never, never>>,
  }
}
